//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Etkinlik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkinlik
    {
        public int id { get; set; }
        public string EtkinlikAd { get; set; }
        public Nullable<int> MekanId { get; set; }
        public Nullable<int> AltKategoriId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> SanatciId { get; set; }
    
        public virtual AltKategori AltKategori { get; set; }
        public virtual Mekan Mekan { get; set; }
        public virtual Sanatci Sanatci { get; set; }
    }
}
