//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Etkinlik.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Proje_EtkinlikEntities : DbContext
    {
        public Proje_EtkinlikEntities()
            : base("name=Proje_EtkinlikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltKategori> AltKategori { get; set; }
        public virtual DbSet<Etkinlik> Etkinlik { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Mekan> Mekan { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<Sahne> Sahne { get; set; }
        public virtual DbSet<Sanatci> Sanatci { get; set; }
        public virtual DbSet<Sehir> Sehir { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
    }
}
