//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Etkinlik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sahne
    {
        public int id { get; set; }
        public Nullable<int> MekanId { get; set; }
        public Nullable<int> KisiSayısı { get; set; }
    
        public virtual Mekan Mekan { get; set; }
    }
}
